apiVersion: v1
kind: Pod
metadata:
  name: nginx-monitored
  namespace: default
  labels:
    app: nginx
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-conf
      mountPath: /etc/nginx/conf.d
  - name: nginx-exporter
    image: nginx/nginx-prometheus-exporter:0.11.0
    args:
      - -nginx.scrape-uri=http://localhost:80/stub_status
    ports:
    - containerPort: 9113
  volumes:
  - name: nginx-conf
    configMap:
      name: nginx-metrics-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-metrics-config
  namespace: default
data:
  stub_status.conf: |
    server {
      listen 80;
      location /stub_status {
        stub_status;
        allow 127.0.0.1;
        deny all;
      }
    }